测试pytorch是否安装成功

In [2]:
import torch

In [3]:
print(torch.cuda.is_available())

True


In [4]:
from torch.backends import cudnn

In [5]:
x = torch.tensor([10.0])
x = x.cuda()

In [9]:
print(cudnn.is_acceptable(x))

True


Tensor基础

In [6]:
import torch

In [7]:
x = torch.tensor([1,2])
y = torch.tensor([3,4])

In [8]:
z = x.add(y)
print(z)
print(x)

tensor([4, 6])
tensor([1, 2])


In [9]:
x.add_(y)
print(x)

tensor([4, 6])


In [11]:
import torch

In [12]:
torch.Tensor([1,2,3,4,5,6])

tensor([1., 2., 3., 4., 5., 6.])

In [13]:
torch.Tensor(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
t = torch.Tensor([[1,2,3],[4,5,6]])

In [18]:
t.size()

torch.Size([2, 3])

In [22]:
t.shape

torch.Size([2, 3])

In [23]:
torch.Tensor(t.size())

tensor([[0., 0., 0.],
        [0., 0., 0.]])

修改tensor形状

In [25]:
import torch

In [26]:
x = torch.rand(2,3)

In [27]:
x.dim()

2

In [28]:
x.view(3,2)

tensor([[0.3977, 0.5763],
        [0.7754, 0.1566],
        [0.3361, 0.6023]])

In [29]:
y = x.view(-1)

In [30]:
y.shape

torch.Size([6])

In [32]:
z = torch.unsqueeze(y,0)
print(z)

tensor([[0.3977, 0.5763, 0.7754, 0.1566, 0.3361, 0.6023]])


In [33]:
z.size()

torch.Size([1, 6])

In [34]:
z.numel()

6

索引操作

In [1]:
import torch

设置一个随机种子

In [36]:
torch.manual_seed(100)

In [5]:
x = torch.randn(2,3)

In [41]:
x[0,:]

tensor([ 0.3607, -0.2859, -0.3938])

In [42]:
x[:,-1]

tensor([-0.3938, -2.3134])

In [43]:
print(x)

tensor([[ 0.3607, -0.2859, -0.3938],
        [ 0.2429, -1.3833, -2.3134]])


In [8]:
mask = x>0

In [9]:
print(mask)

tensor([[False,  True, False],
        [False,  True,  True]])


In [10]:
torch.masked_select(x,mask)

tensor([1.8859, 0.8964, 0.4414])

获取非零下标索引

In [11]:
torch.nonzero(mask)

tensor([[0, 1],
        [1, 1],
        [1, 2]])

In [48]:
torch.nonzero(x)

tensor([[0, 0],
        [0, 1],
        [0, 2],
        [1, 0],
        [1, 1],
        [1, 2]])

In [14]:
index = torch.LongTensor([[0,1,1]])

In [12]:
print(index)

tensor([[0, 1, 1]])


广播机制

In [16]:
import torch
import numpy as np

In [17]:
A = np.arange(0,40,10).reshape(4,1)

In [18]:
B = np.arange(0,3)

In [20]:
print(A)
print(B)

[[ 0]
 [10]
 [20]
 [30]]
[0 1 2]


In [22]:
A1 = torch.from_numpy(A)# 4x1

In [25]:
B1 = torch.from_numpy(B) #3

In [26]:
C = A1 + B1

In [27]:
print(C)

tensor([[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22],
        [30, 31, 32]])


In [28]:
print(C.shape)

torch.Size([4, 3])


In [33]:
print(B2)

tensor([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]])


In [34]:
A2 = A1.expand(4,3)
B2 = B1.expand(4,3)

In [36]:
C1 = A2 + B2

In [39]:
print(C1 == C)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True]])


逐元素操作

In [40]:
import torch

In [41]:
t = torch.randn(1,3)
t1 = torch.randn(3,1)
t2 = torch.randn(1,3)

In [45]:
print(t,'\n',t1,'\n',t2)

tensor([[-0.0083, -1.4349, -0.3941]]) 
 tensor([[ 0.4854],
        [-0.3595],
        [ 1.0975]]) 
 tensor([[-0.4685, -2.4932, -1.5629]])


In [46]:
print(t1/t2)

tensor([[-1.0362, -0.1947, -0.3106],
        [ 0.7675,  0.1442,  0.2300],
        [-2.3428, -0.4402, -0.7022]])


In [47]:
torch.addcdiv(t,0.1,t1,t2)

tensor([[-0.1120, -1.4544, -0.4252],
        [ 0.0684, -1.4205, -0.3711],
        [-0.2426, -1.4789, -0.4643]])

In [48]:
print(t)

tensor([[-0.0083, -1.4349, -0.3941]])


In [49]:
torch.sigmoid(t)

tensor([[0.4979, 0.1923, 0.4027]])

矩阵操作

In [50]:
import torch

In [52]:
a = torch.tensor([2,3])
b = torch.tensor([3,4])

In [53]:
torch.dot(a,b)

tensor(18)

In [54]:
x = torch.randint(10,(2,3))

In [55]:
print(x)

tensor([[9, 7, 1],
        [7, 0, 5]])


In [56]:
y = torch.randint(6,(3,4))

In [57]:
print(y)

tensor([[0, 4, 4, 4],
        [2, 1, 2, 3],
        [3, 0, 5, 3]])


In [58]:
torch.mm(x,y)

tensor([[17, 43, 55, 60],
        [15, 28, 53, 43]])

In [60]:
x = torch.randint(10,(2,2,3))
y = torch.randint(6,(2,3,4))

In [61]:
print(x)

tensor([[[3, 3, 0],
         [7, 4, 0]],

        [[0, 4, 6],
         [6, 1, 9]]])


In [62]:
print(y)

tensor([[[0, 1, 5, 2],
         [5, 5, 0, 3],
         [2, 0, 3, 3]],

        [[4, 5, 1, 4],
         [3, 2, 2, 1],
         [1, 3, 0, 1]]])


In [63]:
torch.bmm(x,y)

tensor([[[15, 18, 15, 15],
         [20, 27, 35, 26]],

        [[18, 26,  8, 10],
         [36, 59,  8, 34]]])

标量反向传播

In [1]:
import torch

In [17]:
x = torch.Tensor([2])

In [18]:
w  =torch.randn(1, requires_grad = True)
b = torch.randn(1, requires_grad = True)

前向传播

In [19]:
y = torch.mul(w,x)
z = torch.add(y,b)

In [20]:
print("x,w,b的requires_grad属性分别为: {},{},{}".format(x.requires_grad, w.requires_grad, b.requires_grad))

x,w,b的requires_grad属性分别为: False,True,True


自动求导,实现梯度方向传播,即梯度的反向传播

In [21]:
z.backward()

In [22]:
print(w.grad)

tensor([2.])


In [23]:
print(x.grad)

None


In [24]:
print(b.grad)

tensor([1.])


非标量反向传播

In [25]:
import torch

In [26]:
x = torch.tensor([[2,3]], dtype = torch.float, requires_grad = True)

In [27]:
J = torch.zeros(2,2)

In [28]:
y = torch.zeros(1,2)

In [29]:
#定义y与x之间的关系:y1 = x1**2 + 3 * x2, y2 = x2**2 + 2*x1